[project]
name = "practica-biocomp"
version = "0.1.0"
description = "Entrega de la pr치ctica de la asignatura Computaci칩n Evolutiva y Bioinspirada del M치ster en Aprendizaje Autom치tico y Datos Masivos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
